# Generated by Django 4.0 on 2021-12-26 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_image', models.ImageField(upload_to='products/', verbose_name='Category Image')),
                ('cate_name', models.CharField(max_length=100, verbose_name='Category name')),
                ('slug', models.SlugField(unique=True)),
                ('code', models.CharField(max_length=50, verbose_name='Category code')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_related', to='ProductApp.category')),
            ],
        ),
    ]
