# Generated by Django 4.0 on 2021-12-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate_image',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Category Image'),
        ),
    ]
