# Generated by Django 4.0 on 2021-12-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0003_alter_category_cate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cate_shot_des',
            field=models.CharField(blank=True, max_length=100, verbose_name='Category name'),
        ),
    ]
