# Generated by Django 4.0 on 2021-12-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0004_category_cate_shot_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate_shot_des',
            field=models.CharField(blank=True, max_length=200, verbose_name='Category short description'),
        ),
    ]
