# Generated by Django 4.0 on 2021-12-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0005_alter_category_cate_shot_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cate_des',
            field=models.TextField(blank=True, verbose_name='Category description'),
        ),
    ]
